baseURL = "https://ouroboros.rocks/"
languageCode = "en-us"
title = "Ouroboros"
theme = "ananke"
enableRobotsTXT = true
DefaultContentLanguage = "en"

[params]
description = "Ouroboros is a decentralized packet network"
favicon = "/images/ouroboros_icon.png"
logo = "/images/ouroboros_compact_64px.png"
featured_image = "/images/ouroboros_bg3.jpg"

[params.copy]
copy = ""

[menu]
[[menu.main]]
name = "Repository"
weight = 40
url = "/cgit"
